# set fps => the latency between existing images
# combine mask and images together

# done 1. first load the first frame which is used for setting boundary 
# done 2. Running Xmem to generate imgs while doing detection 
# 3. Merge the masks with the orignal imgs
# 4. combine with the camera ?? the imgs generated by camera should be saved into the folder which is monitored

import detect_main
import taking_photo
from interactive_demo import xmem_interactive

if __name__ == "__main__":

    fps = 1000
    visualize_every = 3

    folder_name = taking_photo.main()
    xmem_interactive(folder_name)
    
    detect_main.main(folder_name)